# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_proveedor_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='sexo',
            field=models.CharField(choices=[('', 'SELECIONE GENERO'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10),
        ),
    ]
