# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20180124_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10),
        ),
    ]
