# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 21:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cliente', models.PositiveIntegerField(unique=True)),
                ('ci', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('razon_social', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='date')),
            ],
        ),
    ]
