# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 21:42
from __future__ import unicode_literals

import apps.cliente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nacionalidad',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_fijo',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ci',
            field=models.CharField(max_length=10, unique=True, validators=[apps.cliente.models.validate_ci]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('', 'Seleccione Genero'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10),
        ),
    ]
