# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 21:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20180112_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name=''),
        ),
    ]
